### ISSUE TITLE
Would it be possible to remove the 1024 character limit?

### ISSUE THREAD

**Issue by KentonPickard** [mguinness/syslog-framework-logging#2]
I would like to log full exception stack traces but its being cut to 1024 in SysLogLogger.cs on this line:

udp.SendAsync(raw, Math.Min(raw.Length, 1024), _settings.ServerHost, _settings.ServerPort);

Could the max size be configurable?

**Comment by mguinness** [comment]
Adding a setting to SyslogLoggerSettings would be possible, but [RFC 3164](https://tools.ietf.org/html/rfc3164) states that legal syslog messages may not exceed 1024 bytes in length.
