### ISSUE TITLE
Possible race condition

### ISSUE THREAD

**Issue by ti24horas** [mguinness/syslog-framework-logging#4]
https://github.com/mguinness/syslog-framework-logging/blob/3be3f0808bf4bf922249d91cf9148a974ade1a01/src/Syslog.Framework.Logging/SyslogLogger.cs#L86
As per the line above, disposing the connection might lead to race conditions where the udp.sendasync wasn't already completed.
Maybe you could:

upd.SendAsync(msg).ContinueWith(s=> udp.Dispose());

Also, why can't you reuse the udp client? By creating a new udp client in every log request, you can easily cause issues with high garbage collection pressure.

**Comment by mguinness** [comment]
If you submit a PR I'll merge and republish to nuget.

**Comment by mguinness** [comment]
Fixed in PR https://github.com/mguinness/syslog-framework-logging/pull/5 by bbrewder.
