### ISSUE TITLE
Support IOptions framework

### ISSUE THREAD

**Issue by sliekens** [mguinness/syslog-framework-logging#8]
Me and my coworker are trying to figure out how to make SyslogLoggerSettings configurable from appsettings.json. The Readme contains some sample code, but it uses `ctx.Configuration.GetSection("SyslogSettings");` and `Bind()` instead of `IServiceCollection.Configure` and the IOptions framework.

Also this:
>  It is possible to setup Microsoft dependency injection, but that is outside the scope of this article.

Would it be possible to show how? Thanks.

**Comment by mguinness** [comment]
Logging registration has [changed](https://github.com/aspnet/Announcements/issues/255) since this provider was written over 3 years ago but the `SyslogSettings` example provided in README should still work using `Bind()` to retrieve settings from appsettings.json file.  If that doesn't meet your needs a PR with the necessary updates would be welcomed.

**Comment by sliekens** [comment]
Hey @mguinness,

Ideally I'd like to just do this in my Startup.

```csharp
services.Configure<SyslogLoggerSettings>(Configuration.GetSection("Syslog"));
```

I don't think the code supports this pattern right now?

**Comment by mguinness** [comment]
`IOptions` isn't supported in this project, but you can create a PR to add it.

Take a look at [Sending Errors by Email using ILogger](https://jdono.com/2018/05/01/asp-net-core-2-0-c-sending-errors-by-email-using-ilogger/) for an implementation.

**Comment by luber** [comment]
@StevenLiekens I also was looking for this option when .net standard 2.0 was released. But I couldn't find any, so I created [syslog-extensions-logging](https://github.com/luber/syslog-extensions-logging)

**Comment by sliekens** [comment]
@mguinness I could add it as a breaking change, is that acceptable?

**Comment by mguinness** [comment]
Would like to avoid a breaking change if possible.  Can't you add an additional constructor like below into SyslogLoggerProvider?

`public SyslogLoggerProvider(IOptions<SyslogLoggerSettings> settings, string hostName, LogLevel logLevel)`

Then you can add another overloaded method like below into SyslogLoggerFactoryExtensions without SyslogLoggerSettings parameter.

`public static void AddSyslog(this ILoggerFactory loggerFactory, string hostName = null, LogLevel logLevel = LogLevel.Debug)`
