### ISSUE TITLE
Dependency Injection

### ISSUE THREAD

**Issue by michalss** [mguinness/syslog-framework-logging#9]
Hi,
Can you please also include how to do asp.net core 2 dependency injection make work? This is most common usage and it would help a lot of ppl. Also how to use it in Controller? It does not work as expected :( I have to do all manual implementation from sub.

Btw why did u for hell make StructuredData as IEnumerable, that is absolutely bad and not make any reasonable sense :(

Thx

**Comment by mguinness** [comment]
Can you share the code that you're currently using?  As for StructuredData that was added in a PR by @bbrewder so maybe he can explain.

**Comment by michalss** [comment]
```C#
private IOptions<AppSettingsOptions> settings;
private readonly IHttpContextAccessor HttpContextAccessor;
private readonly IHostedService _healthCheck;
private readonly SyslogLoggerProvider mLoggingProvider;
private readonly ILogger mLogger;

public HomeController(IOptions<AppSettingsOptions> settings, IHttpContextAccessor httpContextAccessor, IHostedService healthCheck)
{
    this.settings = settings;
    HttpContextAccessor = httpContextAccessor;
    _healthCheck = healthCheck;

    // Set the Syslog setting here.
    var settingsM = new SysLogImplementation(settings).GetSysLogSettings();
    mLoggingProvider = new SyslogLoggerProvider(settingsM, Environment.MachineName, Microsoft.Extensions.Logging.LogLevel.Debug);
    mLogger = mLoggingProvider.CreateLogger<HomeController>();
}
```
I had to do it this ugly way, since i cannot reach Syslog Settings from appsetttings.json. So i had to move settings under appsettings section. Your implementation from startup does not work, or i have no idea how to use it in controller. Best way would be dependency injection so sure. Also what i missing most is sample project or some complete example code for asp.net core MVC.. :( It could be very usfell but not without this things im missing.. Thx

**Comment by michalss** [comment]
Also i had to make my own class implementation for StructureData. It is really annoying to do it this way..
```C#
using Microsoft.Extensions.Options;
using Notino_Request_Page.Options;
using Syslog.Framework.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Notino_Request_Page.Class
{
    public class SysLogImplementation
    {
        private IOptions<AppSettingsOptions> settings { get; set; }

        public SysLogImplementation(IOptions<AppSettingsOptions> _settings)
        {
            settings = _settings;
        }

        public SyslogLoggerSettings GetSysLogSettings()
        {   
            var settingsM = new SyslogLoggerSettings();
            settingsM.ServerHost = settings.Value.SyslogSettings.ServerHost;
            settingsM.ServerPort = settings.Value.SyslogSettings.ServerPort;
            settingsM.UseUtc = false;
            settingsM.FacilityType = (FacilityType)Enum.Parse(typeof(FacilityType), settings.Value.SyslogSettings.FacilityType.ToString()); 
            settingsM.HeaderType = (SyslogHeaderType)Enum.Parse(typeof(SyslogHeaderType), settings.Value.SyslogSettings.HeaderType.ToString());
            settingsM.MessageTransportProtocol = (Syslog.Framework.Logging.TransportProtocols.TransportProtocol)Enum.Parse(typeof(Syslog.Framework.Logging.TransportProtocols.TransportProtocol), 
                settings.Value.SyslogSettings.MessageTransportProtocol.ToString()); 
            settingsM.StructuredData = GetStructData(settings.Value.SyslogSettings.StructuredData, settings.Value.SyslogSettings.StructuredData[0].Elements);

            return settingsM;
        }

        private IEnumerable<SylogStructuredDataElement> GetElemetns(List<Element> ListElemtns)
        {
            List<SylogStructuredDataElement> elList = new List<SylogStructuredDataElement>();
            foreach (var el in ListElemtns)
            {
                SylogStructuredDataElement elSingle = new SylogStructuredDataElement
                {
                    Name = el.Name,
                    Value = el.Value
                };
                elList.Add(elSingle);
            }

            return elList;
        }

        private IEnumerable<SyslogStructuredData> GetStructData(List<StructuredData> ListStructData, List<Element> ListElemtns)
        {

            List<SyslogStructuredData> elList = new List<SyslogStructuredData>();
            foreach (var el in ListStructData)
            {
                SyslogStructuredData elSingle = new SyslogStructuredData
                {
                    Elements = GetElemetns(ListElemtns),
                    Id = el.Id

                };
                elList.Add(elSingle);
            }

            return elList;
        }
    }
}
```

**Comment by mguinness** [comment]
Are you not able to [add provider](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-2.1#add-providers) under ConfigureLogging?  Then as shown in [ILogger and DependencyInjection in ASP.NET Core 2+](https://stackoverflow.com/questions/52124638/ilogger-and-dependencyinjection-in-asp-net-core-2) you inject the `ILogger` into your controller class.

**Comment by bbrewder** [comment]
> Btw why did u for hell make StructuredData as IEnumerable, that is absolutely bad and not make any reasonable sense :(

The structured data field is enumerable in order to follow the specification. I don't remember enough about the specs to be able to explain why it was done that way, but it seemed to work OK when I was using this code.

https://tools.ietf.org/html/rfc5424
>     6.3.  STRUCTURED-DATA
> 
>    STRUCTURED-DATA provides a mechanism to express information in a well
>    defined, easily parseable and interpretable data format.  There are
>    multiple usage scenarios.  For example, it may express meta-
>    information about the syslog message or application-specific
>    information such as traffic counters or IP addresses.

>    STRUCTURED-DATA can contain zero, one, or multiple structured data
>    elements, which are referred to as "SD-ELEMENT" in this document.

NOTE: I cut off the rest of the description. There might be more information in the spec itself if you are interested in why they did this.
